version: '3.10'

services:
  django:
    build: .
    volumes:
      - ./:/usr/src/app/
    ports:
      - "8000:8000"
    depends_on:
      - pgdb
      - redis
      - celery
    restart: always
    command: >
      sh -c "python manage.py makemigrations backend --noinput &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env

  pgdb:
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    env_file:
      - .env

  celery:
    build: .
    restart: always
    command: celery -A orders worker -l info
    depends_on:
      - redis

  redis:
    image: redis
    restart: always
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    env_file:
      - .env

volumes:
   postgres_data: